// @ts-nocheck -- skip type checking
import * as meta_0 from "../content/docs/meta.json?collection=meta&hash=1761859682028"
import * as docs_9 from "../content/docs/components/navbars.mdx?collection=docs&hash=1761859682028"
import * as docs_8 from "../content/docs/components/inputFields.mdx?collection=docs&hash=1761859682028"
import * as docs_7 from "../content/docs/components/forms.mdx?collection=docs&hash=1761859682028"
import * as docs_6 from "../content/docs/components/cards.mdx?collection=docs&hash=1761859682028"
import * as docs_5 from "../content/docs/components/buttons.mdx?collection=docs&hash=1761859682028"
import * as docs_4 from "../content/docs/components/bantos.mdx?collection=docs&hash=1761859682028"
import * as docs_3 from "../content/docs/hooks/use-auto-resize-textarea.mdx?collection=docs&hash=1761859682028"
import * as docs_2 from "../content/docs/index.mdx?collection=docs&hash=1761859682028"
import * as docs_1 from "../content/docs/components.mdx?collection=docs&hash=1761859682028"
import * as docs_0 from "../content/docs/cli.mdx?collection=docs&hash=1761859682028"
import * as authmeta_0 from "../content/authdocs/meta.json?collection=authmeta&hash=1761859682028"
import * as authdocs_14 from "../content/authdocs/Authentication/session_based_auth.mdx?collection=authdocs&hash=1761859682028"
import * as authdocs_13 from "../content/authdocs/Authentication/role_permission_based_auth.mdx?collection=authdocs&hash=1761859682028"
import * as authdocs_12 from "../content/authdocs/Authentication/production_ready_auth_kits.mdx?collection=authdocs&hash=1761859682028"
import * as authdocs_11 from "../content/authdocs/Authentication/passwordless_auth.mdx?collection=authdocs&hash=1761859682028"
import * as authdocs_10 from "../content/authdocs/Authentication/Oauth_social_logins.mdx?collection=authdocs&hash=1761859682028"
import * as authdocs_9 from "../content/authdocs/Authentication/multifactor_auth.mdx?collection=authdocs&hash=1761859682028"
import * as authdocs_8 from "../content/authdocs/Authentication/custom_auth.mdx?collection=authdocs&hash=1761859682028"
import * as authdocs_7 from "../content/authdocs/Authentication/biometric_authentication.mdx?collection=authdocs&hash=1761859682028"
import * as authdocs_6 from "../content/authdocs/components/User_Profile.mdx?collection=authdocs&hash=1761859682028"
import * as authdocs_5 from "../content/authdocs/components/Signup.mdx?collection=authdocs&hash=1761859682028"
import * as authdocs_4 from "../content/authdocs/components/OTP_Verification.mdx?collection=authdocs&hash=1761859682028"
import * as authdocs_3 from "../content/authdocs/components/Logout.mdx?collection=authdocs&hash=1761859682028"
import * as authdocs_2 from "../content/authdocs/components/Login.mdx?collection=authdocs&hash=1761859682028"
import * as authdocs_1 from "../content/authdocs/index.mdx?collection=authdocs&hash=1761859682028"
import * as authdocs_0 from "../content/authdocs/cli.mdx?collection=authdocs&hash=1761859682028"
import { _runtime } from "fumadocs-mdx/runtime/next"
import * as _source from "../source.config"
export const authdocs = _runtime.doc<typeof _source.authdocs>([{ info: {"path":"cli.mdx","fullPath":"content\\authdocs\\cli.mdx"}, data: authdocs_0 }, { info: {"path":"index.mdx","fullPath":"content\\authdocs\\index.mdx"}, data: authdocs_1 }, { info: {"path":"components/Login.mdx","fullPath":"content\\authdocs\\components\\Login.mdx"}, data: authdocs_2 }, { info: {"path":"components/Logout.mdx","fullPath":"content\\authdocs\\components\\Logout.mdx"}, data: authdocs_3 }, { info: {"path":"components/OTP_Verification.mdx","fullPath":"content\\authdocs\\components\\OTP_Verification.mdx"}, data: authdocs_4 }, { info: {"path":"components/Signup.mdx","fullPath":"content\\authdocs\\components\\Signup.mdx"}, data: authdocs_5 }, { info: {"path":"components/User_Profile.mdx","fullPath":"content\\authdocs\\components\\User_Profile.mdx"}, data: authdocs_6 }, { info: {"path":"Authentication/biometric_authentication.mdx","fullPath":"content\\authdocs\\Authentication\\biometric_authentication.mdx"}, data: authdocs_7 }, { info: {"path":"Authentication/custom_auth.mdx","fullPath":"content\\authdocs\\Authentication\\custom_auth.mdx"}, data: authdocs_8 }, { info: {"path":"Authentication/multifactor_auth.mdx","fullPath":"content\\authdocs\\Authentication\\multifactor_auth.mdx"}, data: authdocs_9 }, { info: {"path":"Authentication/Oauth_social_logins.mdx","fullPath":"content\\authdocs\\Authentication\\Oauth_social_logins.mdx"}, data: authdocs_10 }, { info: {"path":"Authentication/passwordless_auth.mdx","fullPath":"content\\authdocs\\Authentication\\passwordless_auth.mdx"}, data: authdocs_11 }, { info: {"path":"Authentication/production_ready_auth_kits.mdx","fullPath":"content\\authdocs\\Authentication\\production_ready_auth_kits.mdx"}, data: authdocs_12 }, { info: {"path":"Authentication/role_permission_based_auth.mdx","fullPath":"content\\authdocs\\Authentication\\role_permission_based_auth.mdx"}, data: authdocs_13 }, { info: {"path":"Authentication/session_based_auth.mdx","fullPath":"content\\authdocs\\Authentication\\session_based_auth.mdx"}, data: authdocs_14 }]);
export const authmeta = _runtime.meta<typeof _source.authmeta>([{ info: {"path":"meta.json","fullPath":"content\\authdocs\\meta.json"}, data: authmeta_0 }]);
export const docs = _runtime.doc<typeof _source.docs>([{ info: {"path":"cli.mdx","fullPath":"content\\docs\\cli.mdx"}, data: docs_0 }, { info: {"path":"components.mdx","fullPath":"content\\docs\\components.mdx"}, data: docs_1 }, { info: {"path":"index.mdx","fullPath":"content\\docs\\index.mdx"}, data: docs_2 }, { info: {"path":"hooks/use-auto-resize-textarea.mdx","fullPath":"content\\docs\\hooks\\use-auto-resize-textarea.mdx"}, data: docs_3 }, { info: {"path":"components/bantos.mdx","fullPath":"content\\docs\\components\\bantos.mdx"}, data: docs_4 }, { info: {"path":"components/buttons.mdx","fullPath":"content\\docs\\components\\buttons.mdx"}, data: docs_5 }, { info: {"path":"components/cards.mdx","fullPath":"content\\docs\\components\\cards.mdx"}, data: docs_6 }, { info: {"path":"components/forms.mdx","fullPath":"content\\docs\\components\\forms.mdx"}, data: docs_7 }, { info: {"path":"components/inputFields.mdx","fullPath":"content\\docs\\components\\inputFields.mdx"}, data: docs_8 }, { info: {"path":"components/navbars.mdx","fullPath":"content\\docs\\components\\navbars.mdx"}, data: docs_9 }]);
export const meta = _runtime.meta<typeof _source.meta>([{ info: {"path":"meta.json","fullPath":"content\\docs\\meta.json"}, data: meta_0 }]);