// @ts-nocheck -- skip type checking
import * as meta_0 from "../content/docs/meta.json?collection=meta&hash=1761859682028"
import * as docs_1 from "../content/docs/hooks/use-auto-resize-textarea.mdx?collection=docs&hash=1761859682028"
import * as docs_0 from "../content/docs/index.mdx?collection=docs&hash=1761859682028"
import * as authdocs_20 from "../content/authdocs/Mobile Components/userprofile.mdx?collection=authdocs&hash=1761859682028"
import * as authdocs_19 from "../content/authdocs/Mobile Components/sociallogins.mdx?collection=authdocs&hash=1761859682028"
import * as authdocs_18 from "../content/authdocs/Mobile Components/signup.mdx?collection=authdocs&hash=1761859682028"
import * as authdocs_17 from "../content/authdocs/Mobile Components/resetpassword.mdx?collection=authdocs&hash=1761859682028"
import * as authdocs_16 from "../content/authdocs/Mobile Components/register.mdx?collection=authdocs&hash=1761859682028"
import * as authdocs_15 from "../content/authdocs/Mobile Components/otp.mdx?collection=authdocs&hash=1761859682028"
import * as authdocs_14 from "../content/authdocs/Mobile Components/logout.mdx?collection=authdocs&hash=1761859682028"
import * as authdocs_13 from "../content/authdocs/Mobile Components/login.mdx?collection=authdocs&hash=1761859682028"
import * as authdocs_12 from "../content/authdocs/viewprofile.mdx?collection=authdocs&hash=1761859682028"
import * as authdocs_11 from "../content/authdocs/userProfileButton.mdx?collection=authdocs&hash=1761859682028"
import * as authdocs_10 from "../content/authdocs/userprofile.mdx?collection=authdocs&hash=1761859682028"
import * as authdocs_9 from "../content/authdocs/updateProfile.mdx?collection=authdocs&hash=1761859682028"
import * as authdocs_8 from "../content/authdocs/sociallogins.mdx?collection=authdocs&hash=1761859682028"
import * as authdocs_7 from "../content/authdocs/signup.mdx?collection=authdocs&hash=1761859682028"
import * as authdocs_6 from "../content/authdocs/resetpassword.mdx?collection=authdocs&hash=1761859682028"
import * as authdocs_5 from "../content/authdocs/register.mdx?collection=authdocs&hash=1761859682028"
import * as authdocs_4 from "../content/authdocs/otp.mdx?collection=authdocs&hash=1761859682028"
import * as authdocs_3 from "../content/authdocs/logout.mdx?collection=authdocs&hash=1761859682028"
import * as authdocs_2 from "../content/authdocs/login.mdx?collection=authdocs&hash=1761859682028"
import * as authdocs_1 from "../content/authdocs/index.mdx?collection=authdocs&hash=1761859682028"
import * as authdocs_0 from "../content/authdocs/changeCurrrentPassword.mdx?collection=authdocs&hash=1761859682028"
import { _runtime } from "fumadocs-mdx/runtime/next"
import * as _source from "../source.config"
export const authdocs = _runtime.doc<typeof _source.authdocs>([{ info: {"path":"changeCurrrentPassword.mdx","fullPath":"content\\authdocs\\changeCurrrentPassword.mdx"}, data: authdocs_0 }, { info: {"path":"index.mdx","fullPath":"content\\authdocs\\index.mdx"}, data: authdocs_1 }, { info: {"path":"login.mdx","fullPath":"content\\authdocs\\login.mdx"}, data: authdocs_2 }, { info: {"path":"logout.mdx","fullPath":"content\\authdocs\\logout.mdx"}, data: authdocs_3 }, { info: {"path":"otp.mdx","fullPath":"content\\authdocs\\otp.mdx"}, data: authdocs_4 }, { info: {"path":"register.mdx","fullPath":"content\\authdocs\\register.mdx"}, data: authdocs_5 }, { info: {"path":"resetpassword.mdx","fullPath":"content\\authdocs\\resetpassword.mdx"}, data: authdocs_6 }, { info: {"path":"signup.mdx","fullPath":"content\\authdocs\\signup.mdx"}, data: authdocs_7 }, { info: {"path":"sociallogins.mdx","fullPath":"content\\authdocs\\sociallogins.mdx"}, data: authdocs_8 }, { info: {"path":"updateProfile.mdx","fullPath":"content\\authdocs\\updateProfile.mdx"}, data: authdocs_9 }, { info: {"path":"userprofile.mdx","fullPath":"content\\authdocs\\userprofile.mdx"}, data: authdocs_10 }, { info: {"path":"userProfileButton.mdx","fullPath":"content\\authdocs\\userProfileButton.mdx"}, data: authdocs_11 }, { info: {"path":"viewprofile.mdx","fullPath":"content\\authdocs\\viewprofile.mdx"}, data: authdocs_12 }, { info: {"path":"Mobile Components/login.mdx","fullPath":"content\\authdocs\\Mobile Components\\login.mdx"}, data: authdocs_13 }, { info: {"path":"Mobile Components/logout.mdx","fullPath":"content\\authdocs\\Mobile Components\\logout.mdx"}, data: authdocs_14 }, { info: {"path":"Mobile Components/otp.mdx","fullPath":"content\\authdocs\\Mobile Components\\otp.mdx"}, data: authdocs_15 }, { info: {"path":"Mobile Components/register.mdx","fullPath":"content\\authdocs\\Mobile Components\\register.mdx"}, data: authdocs_16 }, { info: {"path":"Mobile Components/resetpassword.mdx","fullPath":"content\\authdocs\\Mobile Components\\resetpassword.mdx"}, data: authdocs_17 }, { info: {"path":"Mobile Components/signup.mdx","fullPath":"content\\authdocs\\Mobile Components\\signup.mdx"}, data: authdocs_18 }, { info: {"path":"Mobile Components/sociallogins.mdx","fullPath":"content\\authdocs\\Mobile Components\\sociallogins.mdx"}, data: authdocs_19 }, { info: {"path":"Mobile Components/userprofile.mdx","fullPath":"content\\authdocs\\Mobile Components\\userprofile.mdx"}, data: authdocs_20 }]);
export const authmeta = _runtime.meta<typeof _source.authmeta>([]);
export const docs = _runtime.doc<typeof _source.docs>([{ info: {"path":"index.mdx","fullPath":"content\\docs\\index.mdx"}, data: docs_0 }, { info: {"path":"hooks/use-auto-resize-textarea.mdx","fullPath":"content\\docs\\hooks\\use-auto-resize-textarea.mdx"}, data: docs_1 }]);
export const meta = _runtime.meta<typeof _source.meta>([{ info: {"path":"meta.json","fullPath":"content\\docs\\meta.json"}, data: meta_0 }]);