import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ViewTransitions } from 'next-view-transitions';
import "./globals.css";
import { ThemeProvider } from "@/components/provider/theme-provider";
import { RootProvider } from "fumadocs-ui/provider"
import { ConvexClientProvider } from "@/provider/ConvexClientProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  
      <ViewTransitions>
      <html lang="en">
        <body
          
          className={` font-sans ${geistSans.variable} ${geistMono.variable} antialiased`}
        >
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
              >
                <RootProvider>
                  <ConvexClientProvider>
                    {children}
                  </ConvexClientProvider>
                </RootProvider>
            </ThemeProvider>
          
        </body>
      </html>
      </ViewTransitions>
    
  );
}
